name: Build and publish docker image

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t ghcr.io/razdeep/cfpredictor:latest
    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Publish image
      run: docker push ghcr.io/razdeep/cfpredictor:latest
    - name: Deploy to heroku
      # uses: gonuit/heroku-docker-deploy@9ab97585f979857642d66612a2ae4062b3347d53
      # This action rebuild the docker image again (though it is built earlier once) and pushes to heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        heroku_app_name: codeforces-rating-predictor
        email: rrajdeeproychowdhury@gmail.com
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
